#+Title: Trip to Nantes, October 1st–14th
#+Author: Martin Gausby

* Organisations and tech stuff
** [[http://www.nantestech.com/en/][#nantestech]]
** [[http://cantine.atlantic2.org][La Cantine par Atlantic 2.0]]
Co-working area which cost 6 euros for half a day, and 12 euros for a full day. This is supposedly where all the tech people meet.

Various events and meet ups can be found here as well.

Location: [[https://maps.google.com/maps?ll=47.21203,-1.551639&z=15&t=m&hl=fr&gl=US&mapclient=embed&cid=2920279127309068674][11 impasse Juton, Nantes]]

Open 9h00-19h00.

** [[http://www.pingbase.net/][PiNG Hackerspace]]
They have three locations; I guess that the Fablab is the most interesting.
*** [[http://www.plateforme-c.org][Fablab Plateforme C]]
Hangar 30, quai des Antilles – 44300 Nantes
*** Bureau
Pôle associatif du 38 Breil (2ème étage), 38 rue du Breil – 44100 Nantes
*** Salle de formation à la PRI Design’in
Design’in, 34 rue Lanoue Bras de Fer – 44200 Nantes

* Event sources
** [[https://www.couchsurfing.com/events/search?utf8=%E2%9C%93&search_query=Nantes%252C+Pays+de+la+Loire%252C+France&latitude=47.218371&longitude=-1.553621&start_date=2015-10-01&end_date=2015-10-14][Couch Surfing events between October 1st and October 14th]]
** [[http://www.meetup.com/find/events/?allMeetups=true&radius=10&userFreeform=Nantes&gcResults=Nantes%252C+France%253AFR%253APays+de+la+Loire%253ALoire-Atlantique%253ANantes%253Anull%253Anull%253A47.218371%253A-1.553621000000021&month=10&day=1&year=2015&eventFilter=all][Meetup.com group events from October 1st onwards]]

** [[http://www.pulsomatic.com/][Pulsomatic.com]]
A french site, but it list most of the concerts, movie screenings and expositions in Nantes.
** [[http://geekevents.fr/calendar/][GeekEvents]]
* Places
** [[http://www.madambla.com/][Madam Blå]]
Sounds like a good place for coffee. Also the owner speaks danish so I should be able to understand what she says.
** [[http://www.lesmachines-nantes.fr/en/][Les Machines de l’île]]
Holy giant wooden elephant, Batman!
