#+Title: Trip to Nantes, October 1st–14th
#+Author: Martin Gausby

* Organisations and tech stuff
** [[http://www.nantestech.com/en/][#nantestech]]
** [[http://www.pingbase.net/][PiNG Hackerspace]]
They have three locations; I guess that the Fablab is the most interesting.
*** [[http://www.plateforme-c.org][Fablab Plateforme C]]
Hangar 30, quai des Antilles – 44300 Nantes
*** Bureau
Pôle associatif du 38 Breil (2ème étage), 38 rue du Breil – 44100 Nantes
*** Salle de formation à la PRI Design’in
Design’in, 34 rue Lanoue Bras de Fer – 44200 Nantes

* Event sources
** [[https://www.couchsurfing.com/events/search?utf8=%E2%9C%93&search_query=Nantes%252C+Pays+de+la+Loire%252C+France&latitude=47.218371&longitude=-1.553621&start_date=2015-10-01&end_date=2015-10-14][Couch Surfing events between October 1st and October 14th]]
** [[http://www.meetup.com/find/events/?allMeetups=true&radius=10&userFreeform=Nantes&gcResults=Nantes%252C+France%253AFR%253APays+de+la+Loire%253ALoire-Atlantique%253ANantes%253Anull%253Anull%253A47.218371%253A-1.553621000000021&month=10&day=1&year=2015&eventFilter=all][Meetup.com group events from October 1st onwards]]

** [[http://www.pulsomatic.com/][Pulsomatic.com]]
A french site, but it list most of the concerts, movie screenings and expositions in Nantes.
** [[http://geekevents.fr/calendar/][GeekEvents]]
* Places
** [[http://www.madambla.com/][Madam Blå]]
Sounds like a good place for coffee. Also the owner speaks danish so I should be able to understand what she says.
** [[http://www.lesmachines-nantes.fr/en/][Les Machines de l’île]]
Holy giant wooden elephant, Batman!

* Calendar
** October 1
*** 19:00 - [[https://www.couchsurfing.com/events/drink-gathering][Drink & Gathering]]
Location: [[https://www.google.com/maps/place/Rue+des+2+Ponts,+44000+Nantes,+France/@47.2167739,-1.5593443,17.72z/data=!4m2!3m1!1s0x4805eea710d5ff19:0x67663a14b34e18ed]["Ta mère", rue des 2 ponts, Nantes]]
*** 20:00 - [[https://twitter.com/firstJnantes][First Jeudi]]
Location: [[https://www.google.com/maps/place/Caf%C3%A9+la+Perle/@47.2131774,-1.556817,17.52z/data=!4m2!3m1!1s0x4805eea7d0cab117:0x985f1855c148c69b][Café la Perle; 8 Rue du Port au Vin; 44000 Nantes]]
** October 2
** October 3
** October 4
*** 20:00 - [[https://www.couchsurfing.com/events/la-rumeur-du-dimanche-nantes-2015-10-04][La Rumeur du dimanche]]
Location: La Rumeur, 2 B Rue Bon Secours, 44000 Nantes, France
** October 5
*** 19:00 - [[http://www.meetup.com/Nantes-Machine-Learning-Meetup/events/224397257/][La régression linéaire et logistique]]
Something, something machine learning.
*** 19:30 - [[https://www.couchsurfing.com/events/b-bel-tower-nantes-2015-10-05][B@bel Tower]]
Location: 6 Rue Bon Secours, Nantes
** October 6
*** 18h30 - Free tour at Platform C
A fablab in Nantes. It seems that tuesdays are their weekly tour day.

Location: [[https://www.google.com/maps/place/Plateforme+C/@47.2042086,-1.570813,17z/data=!4m2!3m1!1s0x4805ec081fef4cd3:0xb95350dd7c2f47e%0A][Plateforme C, Hangar 30, quai des Antilles – 44200 NANTES]]

*** 19:00 - [[http://www.meetup.com/The-Expats-Club/events/225558552/][Expats at Lieu Unique]]
** October 7
** October 8
** October 9
** October 10
** October 11
** October 12
*** 19:30 - [[https://www.couchsurfing.com/events/b-bel-tower-nantes-2015-10-12][B@bel Tower]]
Location: 6 Rue Bon Secours, Nantes
** October 13
*** 19:00 - [[http://humantalks.com/cities/nantes/events/236][Human Talks]]
Location: [[https://www.google.com/maps/place/SAMOA+%252F+cluster+Quartier+de+la+Cr%C3%A9ation/@47.2068036,-1.5617763,17z/data=!3m1!4b1!4m2!3m1!1s0x4805ec01a51adf7f:0xf51a90072f479cdc][Cluster Quartier de la Création Nantes, île de nantes, 44200 Nantes]]
** October 14
** October 15
